services:
  matter:
    image: "ghcr.io/matter-js/python-matter-server:stable"
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - /mnt/Media/MatterData:/data
      - /run/dbus:/run/dbus:ro
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:latest"
    restart: unless-stopped
    volumes:
      - /mnt/Media/HAConfig:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
    environment:
      TZ: Europe/Sofia
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    ports:
      - 13378:80
    volumes:
      - /mnt/Media/AudioBooks:/audiobooks
      - /mnt/Media/Podcasts:/podcasts
      - /mnt/Media/ABConfig:/config
      - /mnt/Media/ABMetadata:/metadata
    environment:
      - TZ=Europe/Sofia
