keys:
  - &monyarm age1vdst8x84mcar4e09v9j4q6a3k8ztfuj326ymtkvyse9e5wfxgslssvpluq
creation_rules:
  - path_regex: secrets/jetbrains/[^/]+\.key$
    key_groups:
      - age:
          - *monyarm
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *monyarm
