# dub-to-nix's resolution of minijson's dub.selections.json, committed like
# Cargo.lock -- unlike Cargo.lock, dub.selections.json carries no checksums
# of its own, so producing this requires a live network lookup against the
# dub registry (verified: dub-to-nix run against minijson's actual source
# this session). That step can't happen inside any nix sandbox without a
# pre-known hash, dynamic derivations or not, so it's regenerated by hand
# (re-run `dub-to-nix` from minijson's source root) whenever
# tools.minijson bumps in sources.toml.
{
  dependencies = {
    argparse = {
      version = "1.4.1";
      sha256 = "1hwpc9y9jqcw849g77pxbz6rvvpslgaxwid1rxpaz4nyhi93fq4g";
    };
    automem = {
      version = "0.6.11";
      sha256 = "0l3cbkji47p9myhdpmm83s4j8rjvdwkyln1hinlw1kzph4dgb5wn";
    };
    bdd = {
      version = "4.1.0";
      sha256 = "0fkfk6rmm72bjy43xy3iv9nmzd2jixcw4wqi4rvsyyw43sggr1dw";
    };
    d-glob = {
      version = "0.5.0";
      sha256 = "1iqnb7fk47sy4xczya5pymmc54s0sg4pbnfs041gyl31iqql0c4c";
    };
    test_allocator = {
      version = "0.3.4";
      sha256 = "1xpjz6smxwgm4walrv3xbzi46cddc80q5n4gs7j9gm2yx11sf7gj";
    };
    unit-threaded = {
      version = "2.2.3";
      sha256 = "070qlnr33miyg6w6q8yvry8nnxng23vdklvbr94dmjrbplxb9fy8";
    };
  };
}
